spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate_search
    username: postgres
    password: root

  jpa:
    properties:
      hibernate:
        search:
          backend:
            analysis:
              configurer: hibernate.config.LuceneAnalyzerConfigurer
#            directory:
#              root: ${elza.workingDir}/lucene/indexes
            lucene_version: LATEST

  mvc:
    hiddenmethod:
      filter:
        enabled: true